// lib/stylecraft-products.ts
// Full catalog scraped from stylecraftus.com/shop.html (177 SKUs across 15 pages).
// Deduplicated to unique product lines — colorway/size variants of the same
// model are merged into a single entry. Pure spare/replacement parts (screws,
// springs, cam followers, foil heads, blade sets, charging cords/bases,
// clipper levers, etc.) are excluded since they have no analyzable competitive
// market of their own. Update periodically.

export const STYLECRAFT_PRODUCTS = [
  // ─── CLIPPERS ──────────────────────────────────────────────
  {
    id: "saber-2-eon",
    name: "Saber 2 Professional Hair Clipper with EON Digital Brushless Motor",
    shortName: "Saber 2 EON Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 319.95,
    url: "https://stylecraftus.com/saber-2-professional-hair-clipper-with-eon-digital-brushless-motor.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "Professional cordless modular hair clipper with EON Digital Brushless Motor. High torque, premium performance for professional barbers. Available in Gold and Black finishes.",
    keyFeatures: ["EON Digital Brushless Motor", "Modular design", "High torque", "Cordless", "Gold/Black finishes"],
    pricePoint: "$319.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["brushless", "professional", "cordless", "premium", "flagship"],
  },
  {
    id: "sc-x-360-jeezy",
    name: "S|C x 360 Jeezy Professional Hair Clipper with IN2 Vector Motor",
    shortName: "360 Jeezy Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 299.95,
    url: "https://stylecraftus.com/s-c-x-360-jeezy-clipper-professional-cordless-hair-clipper-with-in2-vector-motor.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Signature artist-collaboration clipper with the IN2 Vector Motor — limited-run professional cordless clipper.",
    keyFeatures: ["IN2 Vector Motor", "Artist collaboration edition", "Cordless", "Professional grade"],
    pricePoint: "$299.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["vector motor", "collab", "limited edition", "professional"],
  },
  {
    id: "instinct-metal-clipper-in2",
    name: "Instinct Metal Professional Hair Clipper with IN2 Vector Motor",
    shortName: "Instinct Metal Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 299.95,
    url: "https://stylecraftus.com/instinct-metal-clipper-professional-hair-clipper-with-vector-i-t-c-motor.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Professional hair clipper with IN2 Vector Motor. Intelligent torque control adjusts power automatically. All-metal construction.",
    keyFeatures: ["IN2 Vector Motor", "Intelligent Torque Control", "All-metal body", "Cordless professional"],
    pricePoint: "$299.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["vector motor", "intelligent torque", "professional", "all-metal"],
  },
  {
    id: "instinct-clipper-in2",
    name: "Instinct Professional Hair Clipper with IN2 Vector Motor",
    shortName: "Instinct Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 269.95,
    url: "https://stylecraftus.com/instinct-professional-vector-motor-cordless-hair-clipper-with-intuitive-torque-control.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Professional cordless hair clipper with the IN2 Vector Motor and intuitive torque control, in a lightweight polymer body.",
    keyFeatures: ["IN2 Vector Motor", "Intuitive Torque Control", "Lightweight body", "Cordless"],
    pricePoint: "$269.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["vector motor", "professional", "cordless"],
  },
  {
    id: "reign-eon-clipper",
    name: "Reign Professional Hair Clipper with EON Digital Brushless Motor",
    shortName: "Reign EON Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 229.95,
    url: "https://stylecraftus.com/reign-professional-hair-clipper-with-eon-digital-brushless-motor.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "Reign Professional Hair Clipper with EON Digital Brushless Motor. Conquer every style. Available in standard and Purple finishes.",
    keyFeatures: ["EON Digital Brushless Motor", "Professional grade", "Cordless", "Purple finish available"],
    pricePoint: "$229.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["brushless", "professional", "reign collection"],
  },
  {
    id: "rebel-2-c4rbn",
    name: "Rebel 2.0 Professional Hair Clipper with Super C4RBN Motor",
    shortName: "Rebel 2.0 C4RBN Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 199.95,
    url: "https://stylecraftus.com/rebel-2-0-professional-hair-clipper-with-super-c4rbn-motor.html",
    motorType: "Super C4RBN Motor",
    targetMarket: "pro",
    description: "Rebel 2.0 Professional Hair Clipper with Super C4RBN Motor. Rebel with a cause — for barbers who demand more.",
    keyFeatures: ["Super C4RBN Motor", "Professional cordless", "Rebel 2.0 upgrade", "High performance"],
    pricePoint: "$199.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["C4RBN motor", "professional", "rebel collection", "cordless"],
  },
  {
    id: "ubsh-x-sc-rogue-collab",
    name: "S|C x United by Short Hair — Rogue Clipper Collab",
    shortName: "UBSH x Rogue Collab",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 149.95,
    url: "https://stylecraftus.com/s-c-x-united-by-short-hair-rogue-clipper-collab.html",
    motorType: "9V Microchipped Magnetic Motor",
    targetMarket: "pro",
    description: "Limited-run Rogue clipper collaboration with United by Short Hair, sold exclusively through the UBSH channel.",
    keyFeatures: ["9V Microchipped Magnetic Motor", "Limited collab edition", "Cordless", "Exclusive release"],
    pricePoint: "$149.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["magnetic motor", "collab", "limited edition", "rogue collection"],
  },
  {
    id: "rogue-clipper-magnetic",
    name: "Rogue Professional Hair Clipper with Microchipped Magnetic Motor",
    shortName: "Rogue Clipper Magnetic",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 129.95,
    url: "https://stylecraftus.com/rogue-professional-9v-microchipped-magnetic-cordless-hair-clipper.html",
    motorType: "9V Microchipped Magnetic Motor",
    targetMarket: "pro",
    description: "Rogue Professional Hair Clipper with 9V Microchipped Magnetic Motor. Embrace the unconventional.",
    keyFeatures: ["9V Microchipped Magnetic Motor", "Cordless", "Professional grade", "Magnetic motor precision"],
    pricePoint: "$129.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["magnetic motor", "microchipped", "professional", "rogue collection"],
  },
  {
    id: "ergo-clipper-magnetic",
    name: "Ergo Professional Hair Clipper with Microchipped Magnetic Motor",
    shortName: "Ergo Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 129.95,
    url: "https://stylecraftus.com/stylecraft-mag-ergo-linear-clipper.html",
    motorType: "Microchipped Magnetic Motor",
    targetMarket: "pro",
    description: "Ergo Professional Hair Clipper with a linear microchipped magnetic motor, built for an ergonomic in-hand feel during long shifts.",
    keyFeatures: ["Microchipped Magnetic Motor", "Ergonomic linear design", "Cordless", "Professional grade"],
    pricePoint: "$129.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["magnetic motor", "ergonomic", "professional"],
  },
  {
    id: "solecito-rotary",
    name: "Solecito Professional Hair Clipper with Powerful Rotary Motor",
    shortName: "Solecito Rotary Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 109.95,
    url: "https://stylecraftus.com/solecito-professional-hair-clipper-with-powerful-rotary-motor.html",
    motorType: "Powerful Rotary Motor",
    targetMarket: "both",
    description: "Solecito Professional Hair Clipper with Powerful Rotary Motor — professional rotary performance at a mid-tier price.",
    keyFeatures: ["Powerful Rotary Motor", "Professional grade", "Cordless", "Mid-tier pricing"],
    pricePoint: "$109.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["rotary motor", "professional"],
  },
  {
    id: "rival-clipper-digital",
    name: "Rival Metal Hair Clipper with Digital Display",
    shortName: "Rival Metal Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 59.95,
    originalPrice: 79.95,
    url: "https://stylecraftus.com/rival-metal-hair-clipper-with-digital-display.html",
    motorType: "Digital Motor",
    targetMarket: "both",
    description: "Rival Metal Hair Clipper with Digital Display. All-metal construction with digital battery indicator.",
    keyFeatures: ["Digital display", "All-metal body", "Cordless", "Mid-range professional"],
    pricePoint: "$59.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["digital display", "all-metal", "mid-range", "rival collection"],
  },
  {
    id: "ace-cordless-rotary",
    name: "ACE Cordless Hair Clipper with Rotary Motor",
    shortName: "ACE Cordless Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 69.95,
    url: "https://stylecraftus.com/ace-cordless-hair-clipper-with-rotary-motor.html",
    motorType: "Rotary Motor",
    targetMarket: "consumer",
    description: "ACE Cordless Hair Clipper with Rotary Motor. Entry-level professional clipper, frequently discounted.",
    keyFeatures: ["Rotary Motor", "Cordless", "Entry professional", "Budget-friendly"],
    pricePoint: "$69.95",
    amazonCategory: "Hair Clippers",
    tags: ["rotary", "entry level", "cordless", "ace collection"],
  },

  // ─── TRIMMERS ──────────────────────────────────────────────
  {
    id: "instinct-metal-trimmer-in2",
    name: "Instinct Metal Professional Hair Trimmer with IN2 Vector Motor",
    shortName: "Instinct Metal Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 239.95,
    url: "https://stylecraftus.com/instinct-metal-trimmer-professional-hair-trimmer-with-vector-i-t-c-motor.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Instinct Metal Professional Hair Trimmer with IN2 Vector Motor and intelligent torque control in an all-metal body.",
    keyFeatures: ["IN2 Vector Motor", "Intelligent Torque Control", "All-metal body", "Cordless"],
    pricePoint: "$239.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["vector motor", "professional", "all-metal", "trimmer"],
  },
  {
    id: "saber-trimmer-brushless",
    name: "Saber Professional Hair Trimmer with Digital Brushless Motor",
    shortName: "Saber Brushless Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 209.95,
    url: "https://stylecraftus.com/saber-professional-hair-trimmer-with-digital-brushless-motor.html",
    motorType: "Digital Brushless Motor",
    targetMarket: "pro",
    description: "Saber Professional Hair Trimmer with Digital Brushless Motor. High energy, low vibration. Best seller. Available in Gold and Black.",
    keyFeatures: ["Digital Brushless Motor", "Low vibration", "All-metal", "Gold/Black finishes"],
    pricePoint: "$209.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["brushless", "trimmer", "professional", "saber collection", "best seller"],
  },
  {
    id: "precision-saber-trimmer",
    name: "Precision Saber Professional Hair Trimmer with Digital Brushless Motor",
    shortName: "Precision Saber Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 209.95,
    url: "https://stylecraftus.com/precision-saber-full-metal-body-digital-brushless-motor-cordless-hair-trimmer-black.html",
    motorType: "Digital Brushless Motor",
    targetMarket: "pro",
    description: "Precision variant of the Saber trimmer line with a full-metal body and Digital Brushless Motor, tuned for detail line-up work.",
    keyFeatures: ["Digital Brushless Motor", "Full-metal body", "Precision blade geometry", "Cordless"],
    pricePoint: "$209.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["brushless", "trimmer", "precision", "saber collection"],
  },
  {
    id: "instinct-trimmer-in2",
    name: "Instinct Professional Hair Trimmer with IN2 Vector Motor",
    shortName: "Instinct Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 179.95,
    originalPrice: 229.95,
    url: "https://stylecraftus.com/instinct-professional-vector-motor-cordless-hair-trimmer-with-intuitive-torque-control.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Instinct Professional Hair Trimmer with IN2 Vector Motor and intuitive torque control in a lightweight polymer body.",
    keyFeatures: ["IN2 Vector Motor", "Intuitive Torque Control", "Lightweight body", "Cordless"],
    pricePoint: "$179.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["vector motor", "professional", "trimmer"],
  },
  {
    id: "rebel-trimmer-super-torque",
    name: "Rebel Professional Hair Trimmer with Super-Torque Motor",
    shortName: "Rebel Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 139.95,
    url: "https://stylecraftus.com/rebel-professional-modular-super-torque-motor-cordless-hair-trimmer.html",
    motorType: "Super-Torque Motor",
    targetMarket: "pro",
    description: "Rebel Professional Hair Trimmer with a modular Super-Torque Motor for detail and outline work.",
    keyFeatures: ["Super-Torque Motor", "Modular design", "Cordless", "Professional grade"],
    pricePoint: "$139.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["super-torque", "professional", "rebel collection", "trimmer"],
  },
  {
    id: "flex-trimmer",
    name: "Flex Professional Hair Trimmer with Super-Torque Motor",
    shortName: "Flex Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 129.95,
    url: "https://stylecraftus.com/flex-trimmer.html",
    motorType: "Super-Torque Motor",
    targetMarket: "pro",
    description: "Flex Professional Hair Trimmer with Super-Torque Motor, the trimmer half of the Super Set combo.",
    keyFeatures: ["Super-Torque Motor", "Cordless", "Professional grade", "Combo-compatible"],
    pricePoint: "$129.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["super-torque", "professional", "trimmer"],
  },
  {
    id: "reign-trimmer-eon",
    name: "Reign Professional Hair Trimmer with EON Digital Brushless Motor",
    shortName: "Reign EON Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 189.95,
    url: "https://stylecraftus.com/reign-professional-hair-trimmer-with-eon-digital-brushless-motor.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "Reign Professional Hair Trimmer with EON Digital Brushless Motor. Available in standard and Purple finishes.",
    keyFeatures: ["EON Digital Brushless Motor", "Professional grade", "Cordless", "Purple finish available"],
    pricePoint: "$189.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["brushless", "trimmer", "reign collection"],
  },
  {
    id: "ace-trimmer-rotary",
    name: "Ace Hair Trimmer with Rotary Motor",
    shortName: "Ace Rotary Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 59.95,
    url: "https://stylecraftus.com/ace-cordless-precision-hair-trimmer-rechargeable-usb-type-c-3-guards-stainless-steel-blades.html",
    motorType: "Rotary Motor",
    targetMarket: "consumer",
    description: "Ace Hair Trimmer with Rotary Motor, USB-C rechargeable with 3 guide combs and stainless steel blades.",
    keyFeatures: ["Rotary Motor", "USB-C rechargeable", "3 guards included", "Stainless steel blades"],
    pricePoint: "$59.95",
    amazonCategory: "Hair Trimmers",
    tags: ["rotary", "consumer", "usb-c", "ace collection"],
  },
  {
    id: "ace-body-buzzer",
    name: "Ace Body Buzzer Hair Trimmer with Supercharged Rotary Motor",
    shortName: "Ace Body Buzzer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 59.95,
    url: "https://stylecraftus.com/ace-body-buzzer-hair-trimmer-with-supercharged-rotary-motor.html",
    motorType: "Supercharged Rotary Motor",
    targetMarket: "consumer",
    description: "Ace Body Buzzer Hair Trimmer with Supercharged Rotary Motor, purpose-built for body grooming.",
    keyFeatures: ["Supercharged Rotary Motor", "Body-grooming specific", "Cordless", "Waterproof"],
    pricePoint: "$59.95",
    amazonCategory: "Body Groomers",
    tags: ["body groomer", "rotary", "consumer", "ace collection"],
  },
  {
    id: "homie-nano-trimmer",
    name: "Homie Nano Trimmer",
    shortName: "Homie Nano Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 54.95,
    url: "https://stylecraftus.com/homie-nano-trimmer.html",
    motorType: "Nano Motor",
    targetMarket: "consumer",
    description: "Homie Nano Trimmer — compact, portable, precise trimming for home use.",
    keyFeatures: ["Nano motor", "Compact design", "Portable", "Consumer trimmer"],
    pricePoint: "$54.95",
    amazonCategory: "Hair Trimmers",
    tags: ["nano", "compact", "consumer", "home use"],
  },
  {
    id: "ace-beard-blender",
    name: "Ace Beard Blender Hair Trimmer with Supercharged Rotary Motor",
    shortName: "Ace Beard Blender",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 37.95,
    url: "https://stylecraftus.com/ace-beard-blender-trimmer.html",
    motorType: "Supercharged Rotary Motor",
    targetMarket: "consumer",
    description: "Ace Beard Blender Hair Trimmer with Supercharged Rotary Motor, designed for blending beard fades and edges.",
    keyFeatures: ["Supercharged Rotary Motor", "Beard blending", "Cordless", "Compact"],
    pricePoint: "$37.95",
    amazonCategory: "Beard Trimmers",
    tags: ["beard", "rotary", "consumer", "ace collection"],
  },
  {
    id: "schnozzle-nose-ear",
    name: "Schnozzle Water Resistant Nose and Ear Hair Trimmer",
    shortName: "Schnozzle Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 29.95,
    url: "https://stylecraftus.com/schnozzle-water-resistant-nose-and-ear-trimmer-matte-black.html",
    motorType: "Compact Motor",
    targetMarket: "consumer",
    description: "Schnozzle Water Resistant Nose and Ear Hair Trimmer in matte black.",
    keyFeatures: ["Water resistant", "Nose & ear specific", "Compact", "Consumer grooming"],
    pricePoint: "$29.95",
    amazonCategory: "Nose & Ear Trimmers",
    tags: ["nose & ear", "water resistant", "consumer"],
  },
  {
    id: "ace-3in1-trimmer",
    name: "Ace 3-in-1 Rechargeable Multipurpose Hair Trimmer",
    shortName: "Ace 3-in-1 Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 29.95,
    url: "https://stylecraftus.com/ace-3-in-1-rechargeable-multipurpose-hair-trimmer.html",
    motorType: "Rechargeable Motor",
    targetMarket: "consumer",
    description: "Ace 3-in-1 Rechargeable Multipurpose Hair Trimmer. Versatile consumer trimmer for multiple uses.",
    keyFeatures: ["3-in-1 multipurpose", "Rechargeable", "Compact", "Versatile"],
    pricePoint: "$29.95",
    amazonCategory: "Hair Trimmers",
    tags: ["3-in-1", "multipurpose", "rechargeable", "ace collection"],
  },
  {
    id: "ace-ear-nose-dualspeed",
    name: "Ace Electric Ear and Nose Hair Trimmer with Dual-Speed Motor",
    shortName: "Ace Ear & Nose Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 27.95,
    url: "https://stylecraftus.com/ace-electric-ear-and-nose-trimmer-professional-cordless-ear-and-nose-trimmer-with-dual-speed-motor.html",
    motorType: "Dual-Speed Motor",
    targetMarket: "consumer",
    description: "Ace Electric Ear and Nose Hair Trimmer with a Dual-Speed Motor for adjustable precision.",
    keyFeatures: ["Dual-Speed Motor", "Cordless", "Ear & nose specific", "Compact"],
    pricePoint: "$27.95",
    amazonCategory: "Nose & Ear Trimmers",
    tags: ["nose & ear", "dual-speed", "consumer", "ace collection"],
  },

  // ─── SHAVERS ───────────────────────────────────────────────
  {
    id: "instinct-metal-shaver",
    name: "Instinct Metal Professional Double Foil Shaver with IN2 Vector Motor",
    shortName: "Instinct Metal Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 179.95,
    url: "https://stylecraftus.com/instinct-shaver-metal-double-foil-shaver-vector-motor-i-t-c-with-micro-trimmer-black.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Instinct Metal Professional Double Foil Shaver with IN2 Vector Motor and a built-in micro-trimmer. Available in Black and Pink.",
    keyFeatures: ["IN2 Vector Motor", "Double foil head", "Built-in micro-trimmer", "Black/Pink finishes"],
    pricePoint: "$179.95",
    amazonCategory: "Professional Foil Shavers",
    tags: ["foil shaver", "vector motor", "professional", "all-metal"],
  },
  {
    id: "rebel-double-foil-shaver",
    name: "Rebel Professional Double Foil Shaver with Super-Torque Motor",
    shortName: "Rebel Foil Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 84.95,
    url: "https://stylecraftus.com/rebel-electric-mens-foil-shaver-with-super-torque-motor-gold-titanium-foil-head.html",
    motorType: "Super-Torque Motor",
    targetMarket: "pro",
    description: "Rebel Professional Double Foil Shaver with Super-Torque Motor and a gold titanium foil head.",
    keyFeatures: ["Super-Torque Motor", "Double foil head", "Gold titanium foil", "Cordless"],
    pricePoint: "$84.95",
    amazonCategory: "Professional Foil Shavers",
    tags: ["foil shaver", "super-torque", "professional", "rebel collection"],
  },
  {
    id: "ace-waterproof-triple-foil",
    name: "Ace Waterproof Triple Foil Shaver with Integrated Pop-Up Trimmer",
    shortName: "Ace Triple Foil Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 74.95,
    url: "https://stylecraftus.com/ace-waterproof-electric-shaver.html",
    motorType: "Rotary Motor",
    targetMarket: "consumer",
    description: "Ace Waterproof Triple Foil Shaver with an integrated pop-up trimmer for edging.",
    keyFeatures: ["Triple foil head", "Waterproof", "Pop-up trimmer", "Cordless"],
    pricePoint: "$74.95",
    amazonCategory: "Foil Shavers",
    tags: ["foil shaver", "waterproof", "consumer", "ace collection"],
  },
  {
    id: "ace-bald-head-7x",
    name: "Ace Bald Head 7X Foil Shaver with Supercharged Motor",
    shortName: "Ace Bald Head Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 69.95,
    url: "https://stylecraftus.com/ace-bald-head-shaver-professional-7x-foil-bald-head-cordless-shaver-with-supercharged-motor.html",
    motorType: "Supercharged Motor",
    targetMarket: "consumer",
    description: "Ace Bald Head 7X Foil Shaver with a Supercharged Motor, purpose-built for close head shaves.",
    keyFeatures: ["7X foil head", "Supercharged Motor", "Bald-head specific", "Cordless"],
    pricePoint: "$69.95",
    amazonCategory: "Foil Shavers",
    tags: ["foil shaver", "bald head", "consumer", "ace collection"],
  },
  {
    id: "uno-2-single-foil",
    name: "Uno 2.0 Professional Single Foil Shaver with Supercharged Motor",
    shortName: "Uno 2.0 Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 59.95,
    url: "https://stylecraftus.com/uno-2-0-professional-single-foil-usb-c-foil-shaver.html",
    motorType: "Supercharged Motor",
    targetMarket: "both",
    description: "Uno 2.0 Professional Single Foil Shaver with Supercharged Motor and USB-C charging.",
    keyFeatures: ["Single foil head", "USB-C charging", "Supercharged Motor", "Travel-friendly"],
    pricePoint: "$59.95",
    amazonCategory: "Foil Shavers",
    tags: ["foil shaver", "usb-c", "travel", "uno collection"],
  },
  {
    id: "absolute-zero-double-foil",
    name: "Absolute Zero Professional Double Foil Shaver with Rotary Motor",
    shortName: "Absolute Zero Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 49.95,
    url: "https://stylecraftus.com/absolute-zero-pro-foil-shaver-with-built-in-retractable-trimmer-black.html",
    motorType: "Rotary Motor",
    targetMarket: "both",
    description: "Absolute Zero Professional Double Foil Shaver with a built-in retractable trimmer.",
    keyFeatures: ["Double foil head", "Retractable trimmer", "Rotary Motor", "Cordless"],
    pricePoint: "$49.95",
    amazonCategory: "Professional Foil Shavers",
    tags: ["foil shaver", "rotary", "professional"],
  },
  {
    id: "uno-single-foil-turbo",
    name: "Uno Professional Single Foil Shaver with Turbocharged Motor",
    shortName: "Uno Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 49.95,
    url: "https://stylecraftus.com/uno-single-foil-shaver.html",
    motorType: "Turbocharged Motor",
    targetMarket: "both",
    description: "Uno Professional Single Foil Shaver with Turbocharged Motor, USB rechargeable and travel-sized. Available in Red.",
    keyFeatures: ["Single foil head", "Turbocharged Motor", "USB rechargeable", "Travel size"],
    pricePoint: "$49.95",
    amazonCategory: "Foil Shavers",
    tags: ["foil shaver", "travel", "uno collection"],
  },
  {
    id: "ace-single-foil-builtin-trimmer",
    name: "Ace Single Foil Shaver with Built-in Trimmer",
    shortName: "Ace Single Foil Shaver",
    category: "Shavers",
    industry: "grooming-barbering",
    price: 37.95,
    url: "https://stylecraftus.com/ace-single-foil-shaver-with-built-in-trimmer.html",
    motorType: "Compact Motor",
    targetMarket: "consumer",
    description: "Ace Single Foil Shaver with a built-in trimmer for touch-ups on the go.",
    keyFeatures: ["Single foil head", "Built-in trimmer", "Cordless", "Compact"],
    pricePoint: "$37.95",
    amazonCategory: "Foil Shavers",
    tags: ["foil shaver", "consumer", "ace collection"],
  },

  // ─── COMBO SETS ────────────────────────────────────────────
  {
    id: "rogue-combo-set",
    name: "Rogue Combo Set - Professional Cordless Hair Clipper/Trimmer with 9V Magnetic Motor",
    shortName: "Rogue Combo Set",
    category: "Sets",
    industry: "grooming-barbering",
    price: 219.95,
    url: "https://stylecraftus.com/rogue-clipper-trimmer-combo-with-microchipped-magnetic-motor.html",
    motorType: "9V Magnetic Motor",
    targetMarket: "pro",
    description: "Rogue Combo Set with Clipper and Trimmer. 9V Microchipped Magnetic Motor. Best seller combo.",
    keyFeatures: ["Clipper + Trimmer combo", "9V Magnetic Motor", "Microchipped", "Professional set"],
    pricePoint: "$219.95",
    amazonCategory: "Professional Hair Clipper Sets",
    tags: ["combo set", "clipper + trimmer", "magnetic motor", "rogue collection", "best seller"],
  },
  {
    id: "super-set-rebel-flex",
    name: "Super Set - Rebel Cordless Hair Clipper & Flex Cordless Hair Trimmer Set with Super-Torque Rotary Motor",
    shortName: "Super Set (Rebel + Flex)",
    category: "Sets",
    industry: "grooming-barbering",
    price: 199.95,
    url: "https://stylecraftus.com/super-set-rebel-clipper-flex-trimmer-combo-with-travel-case.html",
    motorType: "Super-Torque Rotary Motor",
    targetMarket: "pro",
    description: "Super Set pairing the Rebel Clipper and Flex Trimmer with a Super-Torque Rotary Motor, includes travel case.",
    keyFeatures: ["Clipper + Trimmer combo", "Super-Torque Motor", "Travel case included", "Professional set"],
    pricePoint: "$199.95",
    amazonCategory: "Professional Hair Clipper Sets",
    tags: ["combo set", "clipper + trimmer", "travel case", "rebel collection"],
  },
  {
    id: "rebel-combo-set",
    name: "Rebel Combo Set - Professional Cordless Hair Clipper/Hair Trimmer Set with Super-Torque Motor",
    shortName: "Rebel Combo Set",
    category: "Sets",
    industry: "grooming-barbering",
    price: 189.95,
    url: "https://stylecraftus.com/rebel-professional-super-torque-modular-cordless-hair-clipper-and-trimmer-combo-set.html",
    motorType: "Super-Torque Motor",
    targetMarket: "pro",
    description: "Rebel Combo Set with modular clipper and trimmer sharing a Super-Torque Motor platform.",
    keyFeatures: ["Clipper + Trimmer combo", "Super-Torque Motor", "Modular design", "Professional set"],
    pricePoint: "$189.95",
    amazonCategory: "Professional Hair Clipper Sets",
    tags: ["combo set", "clipper + trimmer", "rebel collection"],
  },
  {
    id: "protege-combo",
    name: "Protégé Combo - Professional Cordless Hair Clipper/Hair Trimmer Combo with Turbocharged Rotary Motor",
    shortName: "Protégé Combo",
    category: "Sets",
    industry: "grooming-barbering",
    price: 179.95,
    url: "https://stylecraftus.com/protege-clipper-trimmer-combo-matte-metallic-black.html",
    motorType: "Turbocharged Rotary Motor",
    targetMarket: "pro",
    description: "Protégé Combo pairing a clipper and trimmer with a Turbocharged Rotary Motor in a matte metallic black finish.",
    keyFeatures: ["Clipper + Trimmer combo", "Turbocharged Rotary Motor", "Matte metallic black", "Professional set"],
    pricePoint: "$179.95",
    amazonCategory: "Professional Hair Clipper Sets",
    tags: ["combo set", "clipper + trimmer", "protege collection"],
  },

  // ─── HAIR DRYERS ───────────────────────────────────────────
  {
    id: "sage-dryer-led",
    name: "Sage Professional Lightweight Hair Dryer with Digital LED Display",
    shortName: "Sage LED Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 199.95,
    url: "https://stylecraftus.com/sage-hair-dryer-professional-lightweight-hairdryer-with-digital-brushless-motor.html",
    motorType: "Digital Brushless Motor",
    targetMarket: "pro",
    description: "Sage Professional Lightweight Hair Dryer with a Digital Brushless Motor and LED temperature display.",
    keyFeatures: ["Digital Brushless Motor", "LED display", "Lightweight", "Professional grade"],
    pricePoint: "$199.95",
    amazonCategory: "Professional Hair Dryers",
    tags: ["brushless", "led display", "professional", "sage collection"],
  },
  {
    id: "sage-2in1-dryer",
    name: "Sage 2-in-1 Diffuser & Hair Dryer with Ion Generator",
    shortName: "Sage Ion Hair Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 99.95,
    url: "https://stylecraftus.com/sage-2-in-1-diffuser-and-hair-dryer-with-ion-generator.html",
    motorType: "Ion Generator Motor",
    targetMarket: "both",
    description: "Sage 2-in-1 Diffuser & Hair Dryer with Ion Generator. Style with wisdom, shine with confidence.",
    keyFeatures: ["Ion Generator", "2-in-1 diffuser", "Professional-grade", "Anti-frizz ions"],
    pricePoint: "$99.95",
    amazonCategory: "Professional Hair Dryers",
    tags: ["ion generator", "diffuser", "2-in-1", "sage collection"],
  },
  {
    id: "stay-temp-dryer-turbo",
    name: "Stay-Temp Professional Hair Dryer with Turbo Power Motor",
    shortName: "Stay-Temp Turbo Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 69.95,
    url: "https://stylecraftus.com/stay-temp-hair-dryer-professional-hair-dryer-with-turbo-power-motor.html",
    motorType: "Turbo Power Motor",
    targetMarket: "both",
    description: "Stay-Temp Professional Hair Dryer with Turbo Power Motor for fast, consistent-heat drying.",
    keyFeatures: ["Turbo Power Motor", "Consistent heat", "Professional grade", "Lightweight"],
    pricePoint: "$69.95",
    amazonCategory: "Professional Hair Dryers",
    tags: ["turbo motor", "professional", "stay-temp collection"],
  },
  {
    id: "ace-foldable-dryer",
    name: "Ace Professional Lightweight Foldable Hair Dryer",
    shortName: "Ace Foldable Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 59.95,
    url: "https://stylecraftus.com/ace-foldable-lightweight-hair-dryer.html",
    motorType: "Standard Motor",
    targetMarket: "consumer",
    description: "Ace Professional Lightweight Foldable Hair Dryer built for travel and everyday consumer use.",
    keyFeatures: ["Foldable design", "Lightweight", "Travel-friendly", "Consumer hair dryer"],
    pricePoint: "$59.95",
    amazonCategory: "Hair Dryers",
    tags: ["foldable", "lightweight", "travel", "ace collection"],
  },
  {
    id: "rival-hair-dryer",
    name: "Rival Lightweight Foldable Hair Dryer",
    shortName: "Rival Foldable Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 39.95,
    originalPrice: 49.95,
    url: "https://stylecraftus.com/rival-lightweight-foldable-hair-dryer.html",
    motorType: "Standard Motor",
    targetMarket: "consumer",
    description: "Rival Lightweight Foldable Hair Dryer. Compact, travel-friendly design.",
    keyFeatures: ["Foldable design", "Lightweight", "Travel-friendly", "Consumer hair dryer"],
    pricePoint: "$39.95",
    amazonCategory: "Hair Dryers",
    tags: ["foldable", "lightweight", "travel", "dryer"],
  },

  // ─── STYLING TOOLS (Irons, Wavers, Hot Brushes) ────────────
  {
    id: "sage-curling-iron-clamp",
    name: "Sage Professional 1\" Cordless Curling Iron & Wand with Removable Clamp",
    shortName: "Sage Cordless Curling Iron",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 129.95,
    url: "https://stylecraftus.com/sage-1-cordless-curling-iron-with-removable-clamp.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Sage Professional 1\" Cordless Curling Iron & Wand with a removable clamp for both clamped and wand-style curling.",
    keyFeatures: ["Cordless", "Removable clamp", "1\" ceramic barrel", "Dual curling styles"],
    pricePoint: "$129.95",
    amazonCategory: "Curling Irons",
    tags: ["cordless", "curling iron", "sage collection"],
  },
  {
    id: "sage-retractable-styling-brush",
    name: "Sage Professional Retractable Styling Brush & Curling Wand 1.25\"",
    shortName: "Sage Styling Brush & Wand",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 99.95,
    url: "https://stylecraftus.com/sage-retractable-styling-brush-and-curling-iron-professional-ceramic-barrel-1-25-inch-retractable-styling-brush-and-curling-iron.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Sage Professional Retractable Styling Brush & Curling Wand with a 1.25\" ceramic barrel — bristles retract for wand-style curling.",
    keyFeatures: ["Retractable bristles", "Ceramic barrel", "1.25\" diameter", "2-in-1 styling"],
    pricePoint: "$99.95",
    amazonCategory: "Hot Brushes",
    tags: ["hot brush", "curling", "sage collection"],
  },
  {
    id: "sage-flat-iron-titanium",
    name: "Sage Professional Flat Iron with 1\" Titanium Plates",
    shortName: "Sage Titanium Flat Iron",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 99.95,
    url: "https://stylecraftus.com/sage-flat-iron-professional-titanium-plates-1-inch-flat-iron.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Sage Professional Flat Iron with 1\" titanium plates for fast, even heat distribution.",
    keyFeatures: ["Titanium plates", "1\" plate width", "Even heat distribution", "Professional grade"],
    pricePoint: "$99.95",
    amazonCategory: "Flat Irons",
    tags: ["flat iron", "titanium", "sage collection"],
  },
  {
    id: "stay-temp-flat-iron",
    name: "Stay-Temp Professional Flat Iron with 1\" Titanium Plates",
    shortName: "Stay-Temp Flat Iron",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 89.95,
    url: "https://stylecraftus.com/stay-temp-flat-iron-professional-1-inch-flat-iron-with-titanium-plates.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Stay-Temp Professional Flat Iron with 1\" titanium plates and consistent temperature hold.",
    keyFeatures: ["Titanium plates", "Stay-Temp heat consistency", "1\" plate width", "Professional grade"],
    pricePoint: "$89.95",
    amazonCategory: "Flat Irons",
    tags: ["flat iron", "titanium", "stay-temp collection"],
  },
  {
    id: "sage-triple-barrel-waver",
    name: "Sage Professional Triple Barrel Deep Waver",
    shortName: "Sage Triple Barrel Waver",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 89.95,
    url: "https://stylecraftus.com/sage-deep-waver-professional-triple-barrel-deep-waver-for-beachy-waves.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Sage Professional Triple Barrel Deep Waver for beachy waves in one pass.",
    keyFeatures: ["Triple barrel", "Deep wave pattern", "Ceramic coated", "Professional grade"],
    pricePoint: "$89.95",
    amazonCategory: "Hair Wavers",
    tags: ["waver", "triple barrel", "sage collection"],
  },
  {
    id: "heat-stroke-hot-brush",
    name: "Heat Stroke Professional Beard & Hair Styling Cordless Hot Brush",
    shortName: "Heat Stroke Hot Brush",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 69.95,
    url: "https://stylecraftus.com/heat-stroke-cordless-beard--styling-hot-brush-black.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Heat Stroke Professional Beard & Hair Styling Cordless Hot Brush for beard straightening and styling.",
    keyFeatures: ["Cordless", "Beard + hair use", "Heated bristles", "Compact"],
    pricePoint: "$69.95",
    amazonCategory: "Hot Brushes",
    tags: ["hot brush", "beard", "cordless"],
  },
  {
    id: "stay-temp-extended-barrel-curling-iron",
    name: "Stay-Temp Professional Ceramic Extended Barrel Curling Iron (0.75\"–1.25\")",
    shortName: "Stay-Temp Extended Barrel Iron",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 54.95,
    url: "https://stylecraftus.com/stay-temp-extended-barrel-curling-iron-professional-ceramic-extended-barrel-1-25-inch-hair-curling-iron.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Stay-Temp Professional Ceramic Extended Barrel Curling Iron, available in 0.75\", 1\", and 1.25\" barrel sizes.",
    keyFeatures: ["Ceramic barrel", "Extended barrel length", "3 size options", "Consistent heat"],
    pricePoint: "$54.95",
    amazonCategory: "Curling Irons",
    tags: ["curling iron", "ceramic", "stay-temp collection"],
  },
  {
    id: "stay-temp-marcel-curling-iron",
    name: "Stay-Temp Professional Ceramic Barrel 3/4\" Marcel Curling Iron",
    shortName: "Stay-Temp Marcel Iron",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 49.95,
    url: "https://stylecraftus.com/stay-temp-marcel-curling-iron-professional-ceramic-barrel-3-4-inch-marcel-hair-curling-iron.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Stay-Temp Professional Ceramic Barrel 3/4\" Marcel Curling Iron for classic clamp-free curling technique.",
    keyFeatures: ["Marcel (clamp-free) style", "Ceramic barrel", "0.75\" diameter", "Consistent heat"],
    pricePoint: "$49.95",
    amazonCategory: "Curling Irons",
    tags: ["curling iron", "marcel", "ceramic", "stay-temp collection"],
  },
  {
    id: "stay-temp-ceramic-curling-iron",
    name: "Stay-Temp Professional Ceramic Barrel Curling Iron (0.5\"–1.5\")",
    shortName: "Stay-Temp Ceramic Curling Iron",
    category: "Styling Tools",
    industry: "haircare-styling",
    price: 44.95,
    url: "https://stylecraftus.com/black-gold-ceramic-professional-curling-iron-1.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Stay-Temp Professional Ceramic Barrel Curling Iron, available across five barrel sizes from 0.5\" to 1.5\".",
    keyFeatures: ["Ceramic barrel", "5 size options", "Black/Gold finish", "Consistent heat"],
    pricePoint: "$44.95",
    amazonCategory: "Curling Irons",
    tags: ["curling iron", "ceramic", "stay-temp collection"],
  },

  // ─── BRUSHES ───────────────────────────────────────────────
  {
    id: "nofrizz-round-brush",
    name: "NoFRIZZ Round Brush with Ion Technology and Ceramic-Coated Barrel",
    shortName: "NoFRIZZ Round Brush",
    category: "Brushes",
    industry: "haircare-styling",
    price: 21.95,
    url: "https://stylecraftus.com/nofrizz-round-brush-with-ion-technology-and-ceramic-coated-barrel-53mm.html",
    motorType: "N/A",
    targetMarket: "consumer",
    description: "NoFRIZZ Round Brush with Ion Technology and a ceramic-coated barrel, available in 32mm, 43mm, and 53mm sizes.",
    keyFeatures: ["Ion technology", "Ceramic-coated barrel", "3 size options", "Anti-frizz"],
    pricePoint: "$21.95–$23.95",
    amazonCategory: "Hair Brushes",
    tags: ["round brush", "ion", "anti-frizz"],
  },
  {
    id: "fresh-cut-barber-brush",
    name: "The Fresh Cut Barber Brush",
    shortName: "Fresh Cut Barber Brush",
    category: "Brushes",
    industry: "grooming-barbering",
    price: 6.95,
    url: "https://stylecraftus.com/the-fresh-cut-professional-fade-and-cleaning-barber-hair-brush.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "The Fresh Cut fade and cleaning barber brush, sold as a single unit or 3-pack in Red or Black.",
    keyFeatures: ["Fade + cleaning brush", "Single or 3-pack", "Red/Black options", "Barber-grade bristles"],
    pricePoint: "$6.95–$13.95",
    amazonCategory: "Barber Brushes",
    tags: ["barber brush", "fade brush", "cleaning brush"],
  },
  {
    id: "no-knuckles-fade-brush",
    name: "No Knuckles - Medium Curved Fade Hair Brush with Natural Bristles",
    shortName: "No Knuckles Fade Brush",
    category: "Brushes",
    industry: "grooming-barbering",
    price: 13.95,
    url: "https://stylecraftus.com/no-knuckles-professional-curved-fade-natural-bristle-brush-medium.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "No Knuckles curved fade brush with natural bristles, ergonomically shaped for fade blending.",
    keyFeatures: ["Curved ergonomic shape", "Natural bristles", "Fade blending", "Barber-grade"],
    pricePoint: "$13.95",
    amazonCategory: "Barber Brushes",
    tags: ["barber brush", "fade brush", "natural bristles"],
  },
  {
    id: "fade-cleaning-wood-brush",
    name: "Fade and Cleaning Hair Brush with Natural Bristles and Wood Handle",
    shortName: "Wood Handle Fade Brush",
    category: "Brushes",
    industry: "grooming-barbering",
    price: 13.95,
    url: "https://stylecraftus.com/barber-fade-brush.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Fade and cleaning hair brush with natural bristles and a wood handle for barber station cleanup.",
    keyFeatures: ["Natural bristles", "Wood handle", "Fade + cleaning", "Barber-grade"],
    pricePoint: "$13.95",
    amazonCategory: "Barber Brushes",
    tags: ["barber brush", "fade brush", "natural bristles"],
  },
  {
    id: "no-knots-detangler",
    name: "No Knots Detangler Brush",
    shortName: "No Knots Detangler",
    category: "Brushes",
    industry: "haircare-styling",
    price: 7.95,
    url: "https://stylecraftus.com/no-knots-detangler-brush.html",
    motorType: "N/A",
    targetMarket: "consumer",
    description: "No Knots Detangler Brush for gentle, snag-free detangling.",
    keyFeatures: ["Flexible bristles", "Detangling", "Consumer haircare", "Compact"],
    pricePoint: "$7.95",
    amazonCategory: "Hair Brushes",
    tags: ["detangler", "consumer"],
  },
  {
    id: "hair-massage-shampoo-brush",
    name: "Hair Massage Shampoo Brush Soft Silicone",
    shortName: "Massage Shampoo Brush",
    category: "Brushes",
    industry: "haircare-styling",
    price: 6.95,
    url: "https://stylecraftus.com/hair-massage-shampoo-brush-soft-silicone-white-orange.html",
    motorType: "N/A",
    targetMarket: "consumer",
    description: "Soft silicone scalp massage brush for use while shampooing.",
    keyFeatures: ["Soft silicone bristles", "Scalp massage", "Shampoo use", "Ergonomic handle"],
    pricePoint: "$6.95",
    amazonCategory: "Hair Brushes",
    tags: ["scalp massager", "silicone", "consumer"],
  },

  // ─── APPAREL ───────────────────────────────────────────────
  {
    id: "sc-x-barber-strong-jacket",
    name: "S|C x Barber Strong Jacket",
    shortName: "Barber Strong Jacket",
    category: "Apparel",
    industry: "grooming-barbering",
    price: 59.95,
    url: "https://stylecraftus.com/sc-x-barber-strong-jacket-1.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "S|C x Barber Strong collaboration jacket for barbers and stylists.",
    keyFeatures: ["Brand collaboration", "Barbershop apparel", "Durable fabric"],
    pricePoint: "$59.95",
    amazonCategory: "Barber Apparel",
    tags: ["apparel", "collab", "merch"],
  },
  {
    id: "water-repellent-apron-adjustable",
    name: "Water-Repellent Barber/Salon Apron with Adjustable Straps",
    shortName: "Adjustable-Strap Apron",
    category: "Apparel",
    industry: "grooming-barbering",
    price: 44.95,
    url: "https://stylecraftus.com/waterproof-barber-salon-apron-with-adjustable-straps-in-radioactive-green.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Water-repellent barber/salon apron with adjustable straps, available in Radioactive Green, Black, and White.",
    keyFeatures: ["Water-repellent fabric", "Adjustable straps", "3 colorways", "Barber/salon use"],
    pricePoint: "$44.95–$49.95",
    amazonCategory: "Barber Aprons",
    tags: ["apron", "water-repellent", "barbershop"],
  },
  {
    id: "waterproof-apron-crossback",
    name: "Waterproof Barber/Salon Apron with Crossback Strap",
    shortName: "Crossback Strap Apron",
    category: "Apparel",
    industry: "grooming-barbering",
    price: 44.95,
    url: "https://stylecraftus.com/heavy-weight-waterproof-professional-barber/salon-apron-cross-back-strap.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Heavy-weight waterproof barber/salon apron with a crossback strap, available in Red/Black, Black, and Black Camo.",
    keyFeatures: ["Heavy-weight waterproof fabric", "Crossback strap", "3 designs", "Barber/salon use"],
    pricePoint: "$44.95",
    amazonCategory: "Barber Aprons",
    tags: ["apron", "waterproof", "barbershop"],
  },
  {
    id: "waterproof-stylist-cape",
    name: "Waterproof Barber/Stylist Cape with Adjustable Closure",
    shortName: "Barber/Stylist Cape",
    category: "Apparel",
    industry: "grooming-barbering",
    price: 27.95,
    url: "https://stylecraftus.com/radioactive-black-barber-stylist-cape.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Waterproof barber/stylist cape with adjustable closure, available in five colorway/camo designs.",
    keyFeatures: ["Waterproof fabric", "Adjustable closure", "5 designs", "Barbershop use"],
    pricePoint: "$27.95",
    amazonCategory: "Barber Capes",
    tags: ["cape", "waterproof", "barbershop"],
  },
  {
    id: "studio-kick-covers-cape",
    name: "Studio Professional Extra-Long Kick Covers Cape",
    shortName: "Kick Covers Cape",
    category: "Apparel",
    industry: "grooming-barbering",
    price: 27.95,
    url: "https://stylecraftus.com/studio-professional-extra-long-kick-covers-cape-in-black.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Studio Professional Extra-Long Kick Covers Cape, available in White and Black.",
    keyFeatures: ["Extra-long coverage", "2 colorways", "Barbershop use"],
    pricePoint: "$27.95",
    amazonCategory: "Barber Capes",
    tags: ["cape", "barbershop"],
  },

  // ─── ACCESSORIES ───────────────────────────────────────────
  {
    id: "universal-magnetic-clipper-guards",
    name: "Universal Magnetic Clipper Guards (8-Pack)",
    shortName: "Magnetic Clipper Guards",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 39.95,
    url: "https://stylecraftus.com/pack-of-8-barber-hairstylist-universal-magnetic-dub-clipper-guards-blue.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "8-pack of universal magnetic clipper guide combs, available in Blue and Black.",
    keyFeatures: ["Magnetic attachment", "8 length guards", "Universal fit", "2 colorways"],
    pricePoint: "$39.95",
    amazonCategory: "Clipper Guards",
    tags: ["guards", "magnetic", "barbershop"],
  },
  {
    id: "tight-guards-neodymium",
    name: "Tight Guards - Barber Hairstylist Dub Neodymium Plastic, 4 Assorted Sizes",
    shortName: "Tight Guards (4-Pack)",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 24.95,
    url: "https://stylecraftus.com/barber-hairstylist-tight-guards-dub-neodymium-plastic-4-assorted-sizes.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "4-pack of close-cutting neodymium magnetic guide combs for tight fades.",
    keyFeatures: ["Neodymium magnetic", "4 assorted sizes", "Tight-fade specific"],
    pricePoint: "$24.95",
    amazonCategory: "Clipper Guards",
    tags: ["guards", "magnetic", "barbershop"],
  },
  {
    id: "studio-mini-nano-mister",
    name: "Studio - Mini Nano Mister 4 Fl Oz",
    shortName: "Mini Nano Mister",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 37.95,
    url: "https://stylecraftus.com/studio-multi-purpose-4-fl-oz-mini-nano-mister.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Studio Mini Nano Mister, a 4 fl oz fine-mist spray bottle for barbershop and salon use.",
    keyFeatures: ["Nano fine mist", "4 fl oz capacity", "Multi-purpose"],
    pricePoint: "$37.95",
    amazonCategory: "Salon Spray Bottles",
    tags: ["mister", "spray bottle", "barbershop"],
  },
  {
    id: "usb-c-charging-dock",
    name: "USB-C Portable Charging Dock Stand",
    shortName: "USB-C Charging Dock",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 21.95,
    url: "https://stylecraftus.com/usb-c-portable-charging-dock-stand-for-hair-clippers-trimmers-shavers-and-type-c-phone-ports.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "USB-C Portable Charging Dock Stand compatible with clippers, trimmers, shavers, and USB-C phones.",
    keyFeatures: ["USB-C compatible", "Multi-device", "Portable stand"],
    pricePoint: "$21.95",
    amazonCategory: "Charging Docks",
    tags: ["charging dock", "usb-c", "accessory"],
  },
  {
    id: "sc-deluxe-straight-razor",
    name: "S|C x Deluxe Line Professional Straight Edge Razor",
    shortName: "Deluxe Straight Razor",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 21.95,
    url: "https://stylecraftus.com/sc-x-deluxe-camo-line-straight-edge-razor-tool-blade-not-included.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "S|C x Deluxe Line Professional Straight Edge Razor tool (blade not included).",
    keyFeatures: ["Straight-edge design", "Deluxe camo finish", "Blade sold separately"],
    pricePoint: "$21.95",
    amazonCategory: "Straight Razors",
    tags: ["razor", "barbershop"],
  },
  {
    id: "sic-pro-station-mat",
    name: "SIC Pro Non Slip Grip Heat Resistant Mat and Station Organizer",
    shortName: "Pro Station Mat",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 19.95,
    url: "https://stylecraftus.com/pro-barber-mat-and-station-organizer.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Non-slip, heat-resistant barber station mat and tool organizer.",
    keyFeatures: ["Heat resistant", "Non-slip grip", "Tool organizer slots"],
    pricePoint: "$19.95",
    amazonCategory: "Barber Station Accessories",
    tags: ["station mat", "organizer", "barbershop"],
  },
  {
    id: "compact-travel-case",
    name: "Compact Travel Case for Clippers, Trimmers, and Shaver Accessories",
    shortName: "Compact Travel Case",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 19.95,
    url: "https://stylecraftus.com/clipper-case.html",
    motorType: "N/A",
    targetMarket: "both",
    description: "Compact travel case sized for clippers, trimmers, and shaver accessories.",
    keyFeatures: ["Compact size", "Multi-tool storage", "Travel-friendly"],
    pricePoint: "$19.95",
    amazonCategory: "Travel Cases",
    tags: ["travel case", "accessory"],
  },
  {
    id: "on-the-go-mirror-case",
    name: "On The Go Barber/Stylist Lightweight Water Resistant Travel Case with Mirror",
    shortName: "On The Go Mirror Case",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 59.95,
    url: "https://stylecraftus.com/on-the-go-barber-stylist-mirror-case.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Lightweight, water-resistant travel case with a built-in mirror for mobile barbers and stylists.",
    keyFeatures: ["Built-in mirror", "Water resistant", "Lightweight", "Mobile barber use"],
    pricePoint: "$59.95",
    amazonCategory: "Travel Cases",
    tags: ["travel case", "mirror", "barbershop"],
  },
  {
    id: "studio-nitrile-gloves",
    name: "Studio - Professional Nitrile Latex Free Gloves with Textured Grip - 100 Count",
    shortName: "Nitrile Gloves (100ct)",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 14.95,
    originalPrice: 31.95,
    url: "https://stylecraftus.com/studio-professional-nitrile-latex-free-gloves-with-textured-grip.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Latex-free nitrile gloves with textured grip, 100-count box, for barbershop and salon use.",
    keyFeatures: ["Latex-free nitrile", "Textured grip", "100-count box"],
    pricePoint: "$14.95",
    amazonCategory: "Salon Gloves",
    tags: ["gloves", "nitrile", "barbershop"],
  },
  {
    id: "flex-latex-gloves",
    name: "FLEX - Professional Latex Gloves - 100 Count",
    shortName: "FLEX Latex Gloves (100ct)",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 9.95,
    originalPrice: 15.95,
    url: "https://stylecraftus.com/flex-professional-latex-gloves-100-count.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Professional latex gloves, 100-count box, for barbershop and salon use.",
    keyFeatures: ["Latex", "100-count box", "Barbershop grade"],
    pricePoint: "$9.95",
    amazonCategory: "Salon Gloves",
    tags: ["gloves", "latex", "barbershop"],
  },
  {
    id: "pro-barber-grip-band-set",
    name: "Pro Barber Hair Clipper and Trimmer Grip Band Set of 2",
    shortName: "Grip Band Set",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 10.95,
    url: "https://stylecraftus.com/professional-barber-hair-clipper-and-trimmer-non-slip-heat-resistant-silicone-grip-band-set-of-2-black-green.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Non-slip, heat-resistant silicone grip bands for clippers and trimmers, set of 2 in Black/Green.",
    keyFeatures: ["Silicone grip band", "Heat resistant", "Set of 2", "Universal fit"],
    pricePoint: "$10.95",
    amazonCategory: "Clipper Accessories",
    tags: ["grip band", "accessory", "barbershop"],
  },
  {
    id: "duster-x-spray",
    name: "Duster-X - Barber & Stylist Duster Spray Aerosol 10 oz.",
    shortName: "Duster-X Spray",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 12.95,
    url: "https://stylecraftus.com/barber-stylist-duster-spray-aerosol-10oz.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Aerosol duster spray for clearing loose hair from clippers and station surfaces.",
    keyFeatures: ["10 oz aerosol", "Barbershop cleanup", "Fast-drying"],
    pricePoint: "$12.95",
    amazonCategory: "Barbershop Supplies",
    tags: ["duster spray", "cleaning", "barbershop"],
  },
  {
    id: "studio-continuous-spray-bottle",
    name: "Studio - Continuous Spray Bottle 6.8 Fl Oz",
    shortName: "Continuous Spray Bottle",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 11.95,
    url: "https://stylecraftus.com/studio-continuous-spray-bottle.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "6.8 fl oz continuous-mist spray bottle for barbershop and salon use.",
    keyFeatures: ["Continuous mist", "6.8 fl oz capacity", "Ergonomic trigger"],
    pricePoint: "$11.95",
    amazonCategory: "Salon Spray Bottles",
    tags: ["spray bottle", "barbershop"],
  },
  {
    id: "clipper-maintenance-kit",
    name: "Clipper Maintenance Oil and Cleaning Brush Kit",
    shortName: "Maintenance Oil & Brush Kit",
    category: "Accessories",
    industry: "grooming-barbering",
    price: 4.95,
    url: "https://stylecraftus.com/spare-maintenance-oil-and-cleaning-brush-kit.html",
    motorType: "N/A",
    targetMarket: "pro",
    description: "Blade oil and cleaning brush kit for routine clipper and trimmer maintenance.",
    keyFeatures: ["Blade oil included", "Cleaning brush included", "Routine maintenance"],
    pricePoint: "$4.95",
    amazonCategory: "Clipper Accessories",
    tags: ["maintenance", "blade oil", "barbershop"],
  },
];

// Helper: get products by industry
export function getProductsByIndustry(industry: string) {
  return STYLECRAFT_PRODUCTS.filter(p => p.industry === industry);
}

// Helper: get product by ID
export function getProductById(id: string) {
  return STYLECRAFT_PRODUCTS.find(p => p.id === id);
}

// Helper: get all clippers
export function getClippers() {
  return STYLECRAFT_PRODUCTS.filter(p => p.category === "Clippers");
}

// Helper: get all motor types
export function getMotorTypes() {
  return Array.from(new Set(STYLECRAFT_PRODUCTS.map(p => p.motorType)));
}

// Helper: unique categories in catalog display order
export const PRODUCT_CATEGORIES = [
  "Clippers",
  "Trimmers",
  "Shavers",
  "Sets",
  "Hair Dryers",
  "Styling Tools",
  "Brushes",
  "Apparel",
  "Accessories",
];
