// lib/stylecraft-products.ts
// Scraped from stylecraftus.com — update periodically

export const STYLECRAFT_PRODUCTS = [
  // ─── CLIPPERS ──────────────────────────────────────────────
  {
    id: "saber-2-eon",
    name: "Saber 2 Professional Hair Clipper with EON Digital Brushless Motor",
    shortName: "Saber 2 EON Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 319.95,
    url: "https://stylecraftus.com/saber-2-professional-hair-clipper-with-eon-digital-brushless-motor.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "Professional cordless modular hair clipper with EON Digital Brushless Motor. High torque, premium performance for professional barbers.",
    keyFeatures: ["EON Digital Brushless Motor", "Modular design", "High torque", "Cordless"],
    pricePoint: "$319.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["brushless", "professional", "cordless", "premium"],
  },
  {
    id: "saber-2-black",
    name: "Saber 2 Professional Hair Clipper with EON Digital Brushless Motor (Black)",
    shortName: "Saber 2 EON Clipper Black",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 319.95,
    url: "https://stylecraftus.com/saber-2-0-clipper-professional-cordless-modular-hair-clipper-with-high-torque-in-black-digital-brushless-motor.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "Professional cordless modular hair clipper with EON Digital Brushless Motor in black finish.",
    keyFeatures: ["EON Digital Brushless Motor", "Modular design", "All-metal body", "Cordless"],
    pricePoint: "$319.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["brushless", "professional", "cordless", "premium", "black"],
  },
  {
    id: "instinct-metal-in2",
    name: "Instinct Metal Professional Hair Clipper with IN2 Vector Motor",
    shortName: "Instinct Metal IN2 Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 299.95,
    url: "https://stylecraftus.com/instinct-metal-clipper-professional-hair-clipper-with-vector-i-t-c-motor.html",
    motorType: "IN2 Vector Motor",
    targetMarket: "pro",
    description: "Professional hair clipper with IN2 Vector Motor. Intelligent torque control adjusts power automatically. All-metal construction.",
    keyFeatures: ["IN2 Vector Motor", "Intelligent Torque Control", "All-metal body", "Cordless professional"],
    pricePoint: "$299.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["vector motor", "intelligent torque", "professional", "all-metal"],
  },
  {
    id: "reign-eon-clipper-purple",
    name: "Reign Professional Hair Clipper with EON Digital Brushless Motor",
    shortName: "Reign EON Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 229.95,
    url: "https://stylecraftus.com/reign-professional-hair-clipper-with-eon-digital-brushless-motor-purple.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "New drop. Reign Professional Hair Clipper with EON Digital Brushless Motor. Conquer every style.",
    keyFeatures: ["EON Digital Brushless Motor", "Professional grade", "Cordless", "New 2024 model"],
    pricePoint: "$229.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["brushless", "new drop", "professional", "reign collection"],
  },
  {
    id: "rebel-2-c4rbn",
    name: "Rebel 2.0 Professional Hair Clipper with Super C4RBN Motor",
    shortName: "Rebel 2.0 C4RBN Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 199.95,
    url: "https://stylecraftus.com/rebel-2-0-professional-hair-clipper-with-super-c4rbn-motor.html",
    motorType: "Super C4RBN Motor",
    targetMarket: "pro",
    description: "Rebel 2.0 Professional Hair Clipper with Super C4RBN Motor. Rebel with a cause — for barbers who demand more.",
    keyFeatures: ["Super C4RBN Motor", "Professional cordless", "Rebel 2.0 upgrade", "High performance"],
    pricePoint: "$199.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["C4RBN motor", "professional", "rebel collection", "cordless"],
  },
  {
    id: "rogue-clipper-magnetic",
    name: "Rogue Professional Hair Clipper with Microchipped Magnetic Motor",
    shortName: "Rogue Clipper Magnetic",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 129.95,
    url: "https://stylecraftus.com/rogue-professional-9v-microchipped-magnetic-cordless-hair-clipper.html",
    motorType: "9V Microchipped Magnetic Motor",
    targetMarket: "pro",
    description: "Rogue Professional Hair Clipper with 9V Microchipped Magnetic Motor. Embrace the unconventional.",
    keyFeatures: ["9V Microchipped Magnetic Motor", "Cordless", "Professional grade", "Magnetic motor precision"],
    pricePoint: "$129.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["magnetic motor", "microchipped", "professional", "rogue collection"],
  },
  {
    id: "rival-clipper-digital",
    name: "Rival Metal Hair Clipper with Digital Display",
    shortName: "Rival Metal Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 79.95,
    url: "https://stylecraftus.com/rival-metal-hair-clipper-with-digital-display.html",
    motorType: "Digital Motor",
    targetMarket: "both",
    description: "Rival Metal Hair Clipper with Digital Display. All-metal construction with digital battery indicator.",
    keyFeatures: ["Digital display", "All-metal body", "Cordless", "Mid-range professional"],
    pricePoint: "$79.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["digital display", "all-metal", "mid-range", "rival collection"],
  },
  {
    id: "solecito-rotary",
    name: "Solecito Professional Hair Clipper with Powerful Rotary Motor",
    shortName: "Solecito Rotary Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 109.95,
    url: "https://stylecraftus.com/solecito-professional-hair-clipper-with-powerful-rotary-motor.html",
    motorType: "Powerful Rotary Motor",
    targetMarket: "both",
    description: "Solecito Professional Hair Clipper with Powerful Rotary Motor. New drop — professional rotary performance.",
    keyFeatures: ["Powerful Rotary Motor", "Professional grade", "Cordless", "New model"],
    pricePoint: "$109.95",
    amazonCategory: "Professional Hair Clippers",
    tags: ["rotary motor", "professional", "new drop"],
  },
  {
    id: "ace-cordless-rotary",
    name: "ACE Cordless Hair Clipper with Rotary Motor",
    shortName: "ACE Cordless Clipper",
    category: "Clippers",
    industry: "grooming-barbering",
    price: 55.95,
    originalPrice: 69.95,
    url: "https://stylecraftus.com/ace-cordless-hair-clipper-with-rotary-motor.html",
    motorType: "Rotary Motor",
    targetMarket: "consumer",
    description: "ACE Cordless Hair Clipper with Rotary Motor. Entry-level professional clipper. On sale.",
    keyFeatures: ["Rotary Motor", "Cordless", "Entry professional", "Budget-friendly"],
    pricePoint: "$55.95",
    amazonCategory: "Hair Clippers",
    tags: ["rotary", "entry level", "cordless", "ace collection"],
  },
  // ─── TRIMMERS ──────────────────────────────────────────────
  {
    id: "saber-trimmer-brushless",
    name: "Saber Professional Hair Trimmer with Digital Brushless Motor",
    shortName: "Saber Brushless Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 209.95,
    url: "https://stylecraftus.com/saber-professional-hair-trimmer-with-digital-brushless-motor.html",
    motorType: "Digital Brushless Motor",
    targetMarket: "pro",
    description: "Saber Professional Hair Trimmer with Digital Brushless Motor. High energy, low vibration. Best seller.",
    keyFeatures: ["Digital Brushless Motor", "Low vibration", "All-metal", "Professional cordless"],
    pricePoint: "$209.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["brushless", "trimmer", "professional", "saber collection"],
  },
  {
    id: "reign-trimmer-eon",
    name: "Reign Professional Hair Trimmer with EON Digital Brushless Motor",
    shortName: "Reign EON Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 189.95,
    url: "https://stylecraftus.com/reign-professional-hair-trimmer-with-eon-digital-brushless-motor-purple.html",
    motorType: "EON Digital Brushless Motor",
    targetMarket: "pro",
    description: "Reign Professional Hair Trimmer with EON Digital Brushless Motor. New drop.",
    keyFeatures: ["EON Digital Brushless Motor", "New drop", "Professional grade", "Cordless"],
    pricePoint: "$189.95",
    amazonCategory: "Professional Hair Trimmers",
    tags: ["brushless", "trimmer", "new drop", "reign collection"],
  },
  {
    id: "homie-nano-trimmer",
    name: "Homie Nano Trimmer",
    shortName: "Homie Nano Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 54.95,
    url: "https://stylecraftus.com/homie-nano-trimmer.html",
    motorType: "Nano Motor",
    targetMarket: "consumer",
    description: "Homie Nano Trimmer — compact, portable, precise trimming for home use.",
    keyFeatures: ["Nano motor", "Compact design", "Portable", "Consumer trimmer"],
    pricePoint: "$54.95",
    amazonCategory: "Hair Trimmers",
    tags: ["nano", "compact", "consumer", "home use"],
  },
  {
    id: "ace-3in1-trimmer",
    name: "Ace 3-in-1 Rechargeable Multipurpose Hair Trimmer",
    shortName: "Ace 3-in-1 Trimmer",
    category: "Trimmers",
    industry: "grooming-barbering",
    price: 29.95,
    url: "https://stylecraftus.com/ace-3-in-1-rechargeable-multipurpose-hair-trimmer.html",
    motorType: "Rechargeable Motor",
    targetMarket: "consumer",
    description: "Ace 3-in-1 Rechargeable Multipurpose Hair Trimmer. Versatile consumer trimmer for multiple uses.",
    keyFeatures: ["3-in-1 multipurpose", "Rechargeable", "Compact", "Versatile"],
    pricePoint: "$29.95",
    amazonCategory: "Hair Trimmers",
    tags: ["3-in-1", "multipurpose", "rechargeable", "ace collection"],
  },
  // ─── COMBO SETS ────────────────────────────────────────────
  {
    id: "rogue-combo-set",
    name: "Rogue Combo Set - Professional Cordless Hair Clipper/Trimmer with 9V Magnetic Motor",
    shortName: "Rogue Combo Set",
    category: "Sets",
    industry: "grooming-barbering",
    price: 169.95,
    originalPrice: 219.95,
    url: "https://stylecraftus.com/rogue-clipper-trimmer-combo-with-microchipped-magnetic-motor.html",
    motorType: "9V Magnetic Motor",
    targetMarket: "pro",
    description: "Rogue Combo Set with Clipper and Trimmer. 9V Microchipped Magnetic Motor. Best seller combo.",
    keyFeatures: ["Clipper + Trimmer combo", "9V Magnetic Motor", "Microchipped", "Professional set"],
    pricePoint: "$169.95",
    amazonCategory: "Professional Hair Clipper Sets",
    tags: ["combo set", "clipper + trimmer", "magnetic motor", "rogue collection"],
  },
  // ─── HAIR DRYERS / BEAUTY ──────────────────────────────────
  {
    id: "rival-hair-dryer",
    name: "Rival Lightweight Foldable Hair Dryer",
    shortName: "Rival Foldable Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 49.95,
    url: "https://stylecraftus.com/rival-lightweight-foldable-hair-dryer.html",
    motorType: "Dryer Motor",
    targetMarket: "consumer",
    description: "Rival Lightweight Foldable Hair Dryer. Compact, travel-friendly design.",
    keyFeatures: ["Foldable design", "Lightweight", "Travel-friendly", "Consumer hair dryer"],
    pricePoint: "$49.95",
    amazonCategory: "Hair Dryers",
    tags: ["foldable", "lightweight", "travel", "dryer"],
  },
  {
    id: "sage-2in1-dryer",
    name: "Sage 2-in-1 Diffuser & Hair Dryer with Ion Generator",
    shortName: "Sage Ion Hair Dryer",
    category: "Hair Dryers",
    industry: "haircare-styling",
    price: 75.95,
    originalPrice: 99.95,
    url: "https://stylecraftus.com/sage-2-in-1-diffuser-and-hair-dryer-with-ion-generator.html",
    motorType: "Ion Generator Motor",
    targetMarket: "both",
    description: "Sage 2-in-1 Diffuser & Hair Dryer with Ion Generator. Style with wisdom, shine with confidence.",
    keyFeatures: ["Ion Generator", "2-in-1 diffuser", "Professional-grade", "Anti-frizz ions"],
    pricePoint: "$75.95",
    amazonCategory: "Professional Hair Dryers",
    tags: ["ion generator", "diffuser", "2-in-1", "sage collection"],
  },
];

// Helper: get products by industry
export function getProductsByIndustry(industry: string) {
  return STYLECRAFT_PRODUCTS.filter(p => p.industry === industry);
}

// Helper: get product by ID
export function getProductById(id: string) {
  return STYLECRAFT_PRODUCTS.find(p => p.id === id);
}

// Helper: get all clippers
export function getClippers() {
  return STYLECRAFT_PRODUCTS.filter(p => p.category === "Clippers");
}

// Helper: get all motor types
export function getMotorTypes() {
  return Array.from(new Set(STYLECRAFT_PRODUCTS.map(p => p.motorType)));
}
