// Shared URL-discovery primitive: given a search query, returns real
// {url, title} pairs actually found by OpenAI's web_search tool.
//
// Deliberately asks for PROSE, not JSON — confirmed this session that
// forcing strict JSON output on a web_search call suppresses url_citation
// annotations entirely (the model can still put real URLs in the JSON
// text, but there's then no independent, server-verifiable signal that
// those URLs came from an actual search rather than the model's own
// invention). Prose mode keeps the annotations, which are generated by
// OpenAI's search infrastructure itself, not freely written by the model —
// the same technique already proven working in lib/product-news.ts.
import { openai, hasOpenAIKey, OPENAI_MODEL } from "./openai";

export interface SearchHit {
  url: string;
  title: string;
}

const SEARCH_TIMEOUT_MS = 25_000;

export function normalizeUrl(url: string): string {
  return (url || "").split("?")[0].replace(/\/$/, "").toLowerCase();
}

export async function searchForUrls(query: string, maxResults = 3): Promise<SearchHit[]> {
  if (!hasOpenAIKey) return [];

  try {
    const response: any = await openai.responses.create(
      {
        model: OPENAI_MODEL,
        reasoning: { effort: "low" },
        tools: [{ type: "web_search" as any }],
        max_tool_calls: 3,
        instructions: `Search the web for: ${query}\n\nBriefly describe what you find in 1-2 sentences with inline citations. Do not narrate your search process.`,
        input: query,
      } as any,
      { timeout: SEARCH_TIMEOUT_MS }
    );

    const message = (response.output || []).find((o: any) => o.type === "message");
    const textBlock = message?.content?.find((c: any) => c.type === "output_text");
    const annotations: any[] = textBlock?.annotations || [];

    const seen = new Set<string>();
    const hits: SearchHit[] = [];
    for (const a of annotations) {
      if (a.type !== "url_citation" || !a.url) continue;
      const key = normalizeUrl(a.url);
      if (seen.has(key)) continue;
      seen.add(key);
      hits.push({ url: a.url, title: a.title || "" });
      if (hits.length >= maxResults) break;
    }
    return hits;
  } catch (err) {
    console.warn(`Web search failed for "${query}":`, err);
    return [];
  }
}
